dist: trusty
sudo: required

services:
  - mongodb

branches: 
  only:
    - master

maxtrix:
  language: node_js
  node_js: 
    - "8.11.1"
  
  include: 
    #Concurrent Tests: Express Unit Tests
      name: "Node Test"
      #Splitting the Node Test into two stages
      cache:
            directories:
              - backend/node_modules
      env:
          - NODE_ENV=unit_test
      install:
          - cd backend && npm install
      script:
          - cd backend && npm run unit_test
          
    #Concurrent Test: Angular Unit Tests
      name: 'Angular Test'

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      cache:
            directories:
              - frontend/node_modules
      before_install: 
        - npm install -g @angular/cli
      
      install:
        - cd frontend && npm install
          
      script: cd frontend && npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          