language: node_js
node_js: 
    - "8.11.1"
dist: trusty
sudo: required

services:
  - mongodb

branches: 
  only:
    - master

matrix:
  
  include: 
    #Concurrent Tests: Express Unit Tests
    - name: "Node Test"
      #Splitting the Node Test into two stages
      cache:
            directories:
              - backend/node_modules
      env:
        - NODE_ENV=unit_test
      before_install: 
        - echo ${TRAVIS_HOME}
        - cd ${HOME}/build/manofthelionarmy/ci_cd_project/backend
      install:
          - npm install
      before_script: 
        - cd ${HOME}/build/manofthelionarmy/ci_cd_project/backend
      script:
          - npm run unit_test
          
    #Concurrent Test: Angular Unit Tests
    - name: 'Angular Test'

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      cache:
            directories:
              - frontend/node_modules
      before_install: 
        - npm install -g @angular/cli
        - cd $frontend
      
      install:
        - npm install
      
      before_script:
        - cd frontend
          
      script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          