language: node_js
node_js: 
  - "8.11.1"
dist: trusty
sudo: required

services:
  - mongodb

branches: 
  only:
    - master

maxtrix:
  include: 
    #Concurrent Tests: Express Unit Tests
    - name: "Node Test"
      #Splitting the Node Test into two stages
      cache:
            directories:
              - backend/node_modules
      jobs:
        - stage: express unit tests
          env:
            - NODE_ENV=unit_test
          install:
            - npm install
          script:
            - npm run unit_test
    #Concurrent Test: Angular Unit Tests
    - name: 'Angular Test'

      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable

      cache:
            directories:
              - frontend/node_modules
      jobs:
        - stage: angular unit tests
          
          install:
            - npm install
          
          script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          