language: node_js
node_js:
- 8.11.1
dist: trusty
sudo: required
services:
- mongodb
branches:
  only:
  - master
matrix:
  include:
  - name: Node Test
    cache:
      directories:
      - backend/node_modules
    env:
    - NODE_ENV=unit_test
    - CI_CD_PROJ=${HOME}/build/manofthelionarmy/ci_cd_project
    before_install:
    - cd ${CI_CD_PROJ}/backend
    install:
    - npm install
    before_script:
    - cd ${CI_CD_PROJ}/backend
    script:
    - npm run unit_test
  - name: Angular Test
    addons:
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
    cache:
      directories:
      - frontend/node_modules
    env:
    - CI_CD_PROJ=${HOME}/build/manofthelionarmy/ci_cd_project
    before_install:
    - npm install -g @angular/cli
    - cd ${CI_CD_PROJ}/frontend
    install:
    - npm install
    before_script:
    - cd ${CI_CD_PROJ}/frontend
    script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
before_install:
#atlas_url, generated by travis
- openssl aes-256-cbc -K $encrypted_ad7ac6b07c2a_key -iv $encrypted_ad7ac6b07c2a_iv
  -in .env.enc -out .env -d
