version: "3.4"

services:
  # set up angular app
  angular:
    build: 
      context: ./frontend
      dockerfile: sample.Dockerfile
      target: test
    image: angular:test
    ports: 
      - "4200:4200"
    networks:
      - frontend
    depends_on: 
      - selenium
      - nodejs 
  # set up selenium     
  selenium:
    image: selenium/hub:3.141
    container_name: selenium
    ports: 
      - "4444:4444"
    networks:
      - frontend
  # set up selenium chrome
  chrome_node: 
    container_name: chrome_node
    depends_on: 
      - selenium
    image: selenium/node-chrome:3.141
    networks: 
      - frontend
  # the nodejs backend
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: nodejs:dev
    container_name: nodejs
    ports: 
      - "3000:3000"
    networks: 
      - frontend
      - backend
    depends_on: 
      - db
    restart: always
  # the mongo database
  db:
    image: mongo
    container_name: db
    networks: 
      - backend
    ports: 
      - "27017:27017"
# the two networks
networks: 
  backend: 
    driver: bridge
  frontend:
    driver: bridge
