
# Nice option to have in the future: https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose
version: "3.4"

services: 
  angular:
    build:
      context: ./frontend
      dockerfile: sample.Dockerfile
      target: development
    image: angular:dev
    container_name: angular
    #stdin_open: true
    #tty: true
    ports: 
      - "4200:4200"
    depends_on: 
      - nodejs
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: nodejs:dev
    container_name: nodejs
    #stdin_open: true
    #tty: true
    ports: 
      - "3000:3000"
    networks: 
      - backend
    depends_on: 
      - db
    restart: always
  db:
    image: mongo
    container_name: db
    networks: 
      - backend
    ports: 
      - "27017:27017"

networks: 
  backend:
    driver: bridge