version: "3.4"

services:
  # set up angular app
  angular:
    build: 
      context: ./frontend
      dockerfile: sample.Dockerfile
      target: test
    image: angular:test
    container_name: angular_test
    ports: 
      - "4200:4200"
    depends_on: 
      - chrome_node
      - nodejs 
    command: npm run e2e -- --protractor-config=e2e/protractor-docker.conf.js #--host 0.0.0.0
  # set up selenium     
  selenium-hub:
    image: selenium/hub:3.141
    environment:
      - GRID_TIMEOUT=10000
    container_name: selenium-hub
    ports: 
      - "4444:4444"
  
  # set up selenium chrome
  chrome_node: 
    image: selenium/node-chrome:3.141
    container_name: chrome_node
    environment: 
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    #shm_size: '2gb'
    depends_on: 
      - selenium-hub
  # the nodejs backend
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: nodejs:dev
    container_name: nodejs
    ports: 
      - "3000:3000"
    networks:
      - backend
    depends_on: 
      - db
    restart: always
  # the mongo database
  db:
    image: mongo
    container_name: db
    networks: 
      - backend
    ports: 
      - "27017:27017"
# the two networks
networks: 
  backend: 
    driver: bridge
