version: "3.4"

services:
  # set up angular app
  angular:
    build: 
      context: ./frontend
      dockerfile: sample.Dockerfile
      target: test
    image: angular:test
    container_name: angular
    ports: 
      - "4200:4200"
    volumes: 
      - /dev/shm:/dev/shm
    depends_on: 
      - nodejs 
    networks: 
      - frontend
    command: npm run e2e -- --protractor-config=e2e/protractor-docker.conf.js --host 0.0.0.0 --webdriver-update=false
 
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: nodejs:dev
    container_name: nodejs
    ports: 
      - "3000:3000"
    networks:
      - backend
      - frontend
    depends_on: 
      - db
    restart: always
  # the mongo database
  db:
    image: mongo
    container_name: db
    networks: 
      - backend
    ports: 
      - "27017:27017"
  protractor:
    build:
      context: ./frontend
      dockerfile: sample.Dockerfile
      target: test
    image: angular:test
    container_name: protractor
    ports: 
      - "9876:9876"
    privileged: true
    networks: 
      - grid
      - frontend
    depends_on:
      - selenium-hub
      - chrome_node
      - e2e
    command: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false --dev-server-target= 
# the two networks
networks: 
  backend: 
    driver: bridge
  frontend:
    driver: bridge
  grid:
    driver: bridge