
# Nice option to have in the future: https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose
version: "3.4"

services: 
  proxy: 
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    ports: 
      - "80:80"
  angular:
    build:
      context: ./frontend
      dockerfile: sample.Dockerfile
      target: development
    image: angular:dev
    container_name: angular
    networks: 
      - frontend
    ports: 
      - "4200:4200"
    depends_on: 
      - nodejs
      - proxy
  nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: nodejs:dev
    container_name: nodejs
    hostname: nodejs
    domainname: nodejs
    ports: 
      - "3000:3000"
    networks: 
      - backend
      - frontend
    depends_on: 
      - db
    restart: always
  db:
    image: mongo
    container_name: db
    networks: 
      - backend
    ports: 
      - "27017:27017"

networks: 
  backend:
    driver: bridge
  frontend:
    driver: bridge